name: restauran_app_dicoding
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  android_alarm_manager_plus: ^3.0.4
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  device_preview: ^1.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^16.3.0
  flutter_rating_bar: ^4.0.1
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  http: ^1.1.2
  intl: ^0.18.1
  loading_animation_widget: ^1.2.0+4
  lottie: ^3.0.0
  mockito: ^5.4.4
  path_provider: ^2.1.2
  readmore: ^2.2.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.jpg
    - assets/animation/empty.json
